'''
P.S: You are given two strings s and t. String t is generated by random shuffling string s and then add one more letter at a random position.
Return the letter that was added to t.
'''

#Solution:
class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        s=sorted(s)
        t=sorted(t)
        for x in range(len(s)):
            if s[x]!=t[x]:
                return s[x]
        return t[x+1]
