'''
P.S: You are given two strings s and t. String t is generated by random shuffling string s and then add one more letter at a random position.
Return the letter that was added to t.
'''

#Solution:
class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        t=list(t)
        for x in s:
            if x in t:
                t.remove(x)
        if len(t)!=0:
            return t[-1]
